language: python
python:
  - "2.6"
  - "2.7"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib; fi"
  - pip install -e .
  - cp tests/config.py revere/config.py
  - pip install -r requirements/tests.txt
script:
  - make test
after_script:
  coveralls
